/* OPERATION MK — WEEK 1 · SCENE 01 v4 「진짜 왔네」
   Dialogue Set: dialogue-week1-scene001-v4
   Scene: week1-scene-001 (Sydney Airport Arrival Area, 09:30)
   Loaded into /dev/game for VN UX testing. */

// role 'protagonist' gets its own dedicated CharacterTransform; every other
// role shares one common default transform (see DevGameState in assetDb.js) —
// tune it once on any non-protagonist character and it applies to all of them.
const dialogueCharacters = [
  { id: 'jisoo', name: '지수', role: 'protagonist' },
  { id: 'youngwoo', name: '영우', role: 'other' }
];

// Every dialogue line's `expression` field is one of these ids — 인물 DB
// (character upload) registers one image per (character, expression) pair,
// and /dev/game looks that pair up to pick the portrait for each line.
const dialogueExpressions = [
  { id: 'neutral', label: '기본' },
  { id: 'happy', label: '기쁨' },
  { id: 'annoyed', label: '짜증' },
  { id: 'shocked', label: '놀람' },
  { id: 'soft', label: '다정' },
  { id: 'smirk', label: '장난' },
  { id: 'suspicious', label: '의심' },
  { id: 'blank', label: '멍함' },
  { id: 'curious', label: '호기심' },
  { id: 'serious', label: '진지' },
];

// Pure stage-direction beats (no speaker) use characterId to say who, if
// anyone, stays on screen for that beat — keeps the portrait from flickering
// out and back in across a beat with no line of its own.
const week1Scene001Lines = [
  { id: 'line-001', speaker: '', text: '시드니 공항.\n오전 9시 30분.', characterId: null },
  { id: 'line-002', speaker: '', text: '긴 비행 끝에 도착한 지수는\n도착 게이트 앞에서 같은 곳을 네 번째로 둘러보고 있었다.', characterId: null },
  { id: 'line-003', speaker: '지수', text: '아 진짜.\n어디 있는 거야 대체.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-004', speaker: '지수', text: '분명 바로 보인댔는데.\n그 바로가 대체 누구 기준이야.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-005', speaker: '지수', text: '쌤?\n저 도착했어요.', characterId: 'jisoo', expression: 'neutral' },
  { id: 'line-006', speaker: '지수', text: '설마\n아직도 집이에요…?', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-007', speaker: '영우', text: '지수야아 ㅎㅎㅎㅎ', characterId: null },
  { id: 'line-008', speaker: '지수', text: '...어?', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-009', speaker: '영우', text: '여기여기 ㅎㅎㅎㅎㅎ', characterId: null },
  { id: 'line-010', speaker: '', text: '지수가 뒤를 돌아본다.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-011', speaker: '지수', text: '헐.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-012', speaker: '지수', text: '쌤!!!!', characterId: 'jisoo', expression: 'happy' },
  { id: 'line-013', speaker: '영우', text: 'ㅎㅎㅎㅎㅎㅎ\n왜 이제 왔어 바부야', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-014', speaker: '지수', text: '아니 내가 왜 이제 와!\n비행기가 이제 왔는데!', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-015', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n맞네\n내가 잘못했네', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-016', speaker: '지수', text: '아 뭐예요 시작부터,\n진짜.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-017', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n아 근데 진짜 왔네', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-018', speaker: '지수', text: '그러게.', characterId: 'jisoo', pauseBeforeMs: 300, expression: 'soft' },
  { id: 'line-019', speaker: '영우', text: '개신기하다', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-020', speaker: '지수', text: '뭐가요?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-021', speaker: '영우', text: '그냥\n맨날 폰으로만 보던 지수가\n진짜 여기 있자나', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-022', speaker: '지수', text: '...', characterId: 'jisoo', pauseBeforeMs: 400, expression: 'blank' },
  { id: 'line-023', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n너무 조은데', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-024', speaker: '지수', text: '나도.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-025', speaker: '지수', text: '근데 잠깐.', characterId: 'jisoo', pauseBeforeMs: 300, expression: 'curious' },
  { id: 'line-026', speaker: '영우', text: '웅?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-027', speaker: '지수', text: '언제부터 여기 있었어요?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-028', speaker: '영우', text: '나?\n음...\n아까부터?', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-029', speaker: '지수', text: '아까부터요?????', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-030', speaker: '영우', text: '웅웅', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-031', speaker: '지수', text: '아니\n근데 왜 말 안 했어요?', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-032', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 지수가 계속 찾고 있길래\n나도 모르게 보고 있었어', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-033', speaker: '지수', text: '와.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-034', speaker: '영우', text: '미안미안 ㅎㅎㅎㅎ\n근데 진짜 너무 열심히 찾더라', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-035', speaker: '지수', text: '아 당연히 찾죠!\n저 쌤 찾으러 온 건데!', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-036', speaker: '영우', text: '아 그러네', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-037', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n생각해보니까 너무 당연한 말이네', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-038', speaker: '지수', text: '진짜 얼탱.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-039', speaker: '지수', text: '아니 잠깐.\n이거 약간 그런 거 아니에요?', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-040', speaker: '영우', text: '머가?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-041', speaker: '지수', text: '“호주에 도착한 여자친구는\n남자친구를 몇 분 안에 찾을 수 있을까요?”', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-042', speaker: '지수', text: '이런 사회실험.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-043', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n사회실험은 뭐야 진짴ㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-044', speaker: '', text: '영우가 한참 웃는다.', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-045', speaker: '영우', text: '아니 근데\n그렇게 말하니까 내가 진짜 개이상한 사람이자나', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-046', speaker: '지수', text: '아니에요?', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-047', speaker: '영우', text: '아니야아', characterId: 'youngwoo', expression: 'annoyed' },
  { id: 'line-048', speaker: '지수', text: '확실해요?', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-049', speaker: '영우', text: '...', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-050', speaker: '영우', text: '한 80퍼 정도?', characterId: 'youngwoo', expression: 'smirk' },
  { id: 'line-051', speaker: '지수', text: '미친.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-052', speaker: '', text: '지수가 웃음을 터뜨린다.', characterId: 'jisoo', expression: 'happy' },
  { id: 'line-053', speaker: '지수', text: '아 진짜.\n하나도 안 변했어 ㅋㅎㅋㅎ', characterId: 'jisoo', expression: 'happy' },
  { id: 'line-054', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n왜\n실망했어?', characterId: 'youngwoo', expression: 'smirk' },
  { id: 'line-055', speaker: '', text: '지수가 잠깐 영우를 본다.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-056', speaker: '지수', text: '아니.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-057', speaker: '지수', text: '다행이지.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-058', speaker: '영우', text: '엉?\n뭐가 다행이야', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-059', speaker: '지수', text: '몰라도 돼.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-060', speaker: '영우', text: '아니 말해놓고 왜 도망가아', characterId: 'youngwoo', expression: 'annoyed' },
  { id: 'line-061', speaker: '지수', text: '응.\n일부러.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-062', speaker: '영우', text: '아놔\n호주 오자마자 더 못돼졌네', characterId: 'youngwoo', expression: 'annoyed' },
  { id: 'line-063', speaker: '지수', text: '저 방금 도착했거든요 쌤.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-064', speaker: '지수', text: '그리고 이건 원래 쌤한테 배운 거예요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-065', speaker: '영우', text: '내가 언제어', characterId: 'youngwoo', expression: 'annoyed' },
  { id: 'line-066', speaker: '지수', text: '지금도 하고 있잖아요.\n사람 계속 보고만 있기.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-067', speaker: '영우', text: '아니 그건', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-068', speaker: '영우', text: '반가워서 봤지', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-069', speaker: '영우', text: '진짜 왔구나 싶어서', characterId: 'youngwoo', pauseBeforeMs: 400, expression: 'soft' },
  { id: 'line-070', speaker: '', text: '지수 표정 변화.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-071', speaker: '지수', text: '...', characterId: 'jisoo', expression: 'blank' },
  { id: 'line-072', speaker: '영우', text: '왜애', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-073', speaker: '지수', text: '아니.\n갑자기 그런 말 하면 제가 뭐라 그래요.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-074', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n그냥 조으면 좋다고 하는 거지', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-075', speaker: '지수', text: '아 진짜.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-076', speaker: '영우', text: '지수 그거 무겁지 않아?', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-077', speaker: '지수', text: '뭐가요?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-078', speaker: '영우', text: '캐리어\n줘봐 내가 들게', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-079', speaker: '지수', text: '오.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-080', speaker: '지수', text: '잠깐만요.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-081', speaker: '영우', text: '왜왜', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-082', speaker: '지수', text: '지금 기록해야 돼.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-083', speaker: '영우', text: '뭘 또 기록해', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-084', speaker: '지수', text: '“2026년.\n서영우 씨.\n시드니 공항에서 여자친구 캐리어 자발적 운반.”', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-085', speaker: '지수', text: '역사적인 순간이잖아요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-086', speaker: '영우', text: 'ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아 그러면 안 들래', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-087', speaker: '지수', text: '아니 왜요!!', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-088', speaker: '영우', text: '부담스럽자나\n기록 남긴다며 ㅋㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-089', speaker: '지수', text: '아니 그건 그거고.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-090', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 “그건 그거고”는 뭐야', characterId: 'youngwoo', pauseBeforeMs: 200, expression: 'happy' },
  { id: 'line-091', speaker: '지수', text: '...', characterId: 'jisoo', expression: 'blank' },
  { id: 'line-092', speaker: '영우', text: '아 너무 웃기네 진짜', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-093', speaker: '지수', text: '아 됐어요.\n들어주세요.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-094', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n갑자기 공손해졌네', characterId: 'youngwoo', expression: 'smirk' },
  { id: 'line-095', speaker: '지수', text: '쌤이잖아요.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-096', speaker: '지수', text: '내 사람한테는 정성 다해야죠.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-097', speaker: '영우', text: '아...', characterId: 'youngwoo', pauseBeforeMs: 400, expression: 'blank' },
  { id: 'line-098', speaker: '영우', text: '그렇게 말하면 내가 뭐라 하냐', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-099', speaker: '지수', text: '그치?\n이겼다.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-100', speaker: '영우', text: '이게 언제부터 승부였엌ㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-101', speaker: '지수', text: '방금부터.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-102', speaker: '영우', text: '규칙도 없이?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-103', speaker: '지수', text: '응.\n내가 만들 거야.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-104', speaker: '영우', text: '아 진짜 지수답다', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-105', speaker: '지수', text: '칭찬이에요?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-106', speaker: '영우', text: '웅웅\n개칭찬', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-107', speaker: '지수', text: '흠.\n인정.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-108', speaker: '', text: '둘이 걷기 시작한다.\n공항 배경음이 약간 줄어든다.', characterId: null },
  { id: 'line-109', speaker: '지수', text: '근데 쌤.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-110', speaker: '영우', text: '웅웅', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-111', speaker: '지수', text: '나 진짜 시드니 온 거 아직 좀 이상해요.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-112', speaker: '영우', text: '아 그래?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-113', speaker: '지수', text: '그냥...\n맨날 사진으로만 보던 데잖아요.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-114', speaker: '지수', text: '오페라하우스 있고.\n하버브리지 있고.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-115', speaker: '지수', text: '그리고 거기에 영우가 있고.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-116', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ', characterId: 'youngwoo', pauseBeforeMs: 400, expression: 'happy' },
  { id: 'line-117', speaker: '지수', text: '그게 제일 이상해.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-118', speaker: '영우', text: '나도 그래', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-119', speaker: '지수', text: '진짜?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-120', speaker: '영우', text: '웅', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-121', speaker: '영우', text: '맨날 화면에 있던 지수가\n진짜 앞에 있으니까', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-122', speaker: '영우', text: '개조아', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-123', speaker: '지수', text: '나도 개조아.', characterId: 'jisoo', pauseBeforeMs: 300, expression: 'happy' },
  { id: 'line-124', speaker: '', text: '둘이 잠깐 웃는다.', characterId: null },
  { id: 'line-125', speaker: '지수', text: '근데 쌤.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-126', speaker: '영우', text: '웅?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-127', speaker: '지수', text: '생각해보니까 좀 이상한데.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-128', speaker: '영우', text: '머가 또', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-129', speaker: '지수', text: '쌤이 너무 정상적이에요.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-130', speaker: '영우', text: '아니 그게 무슨 말이야', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-131', speaker: '지수', text: '아니 봐봐요.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-132', speaker: '지수', text: '공항 마중.\n캐리어 들어줌.\n밥.\n숙소.\n내일부터 관광.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-133', speaker: '지수', text: '너무 정상적이잖아요.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-134', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n내가 정상적이면 왜 수상한데', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-135', speaker: '지수', text: '쌤이니까요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-136', speaker: '영우', text: '아니 설명이 하나도 안 됐자나', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-137', speaker: '지수', text: '저한텐 돼요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-138', speaker: '영우', text: '아놔 진짜', characterId: 'youngwoo', expression: 'annoyed' },
  { id: 'line-139', speaker: '지수', text: '그래서 진짜 뭐 없어요?', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-140', speaker: '영우', text: '뭐가 없어', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-141', speaker: '지수', text: '뭐 준비한 거.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-142', speaker: '영우', text: '밥 준비했지', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-143', speaker: '지수', text: '...', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-144', speaker: '영우', text: '배 안 고파?', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-145', speaker: '지수', text: '고프긴 한데.', characterId: 'jisoo', expression: 'blank' },
  { id: 'line-146', speaker: '영우', text: '그치\n일단 우리 지수 밥부터 먹자', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-147', speaker: '지수', text: '아니 말 돌리지 마.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-148', speaker: '영우', text: '안 돌렸어어\n진짜 배고플 것 같아서 그러지', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-149', speaker: '지수', text: '쌤.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-150', speaker: '영우', text: '네에', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-151', speaker: '지수', text: '방금 존댓말 쓴 거 더 수상해요.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-152', speaker: '영우', text: '아', characterId: 'youngwoo', pauseBeforeMs: 200, expression: 'blank' },
  { id: 'line-153', speaker: '영우', text: '망했네', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-154', speaker: '', text: '지수가 웃음을 터뜨린다.', characterId: 'jisoo', expression: 'happy' },
  { id: 'line-155', speaker: '지수', text: '아 진짜.', characterId: 'jisoo', expression: 'happy' },
  { id: 'line-156', speaker: '영우', text: 'ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 왜 이렇게 눈치가 빨라', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-157', speaker: '', text: '지수 표정 변화.', characterId: 'jisoo', pauseBeforeMs: 300, expression: 'smirk' },
  { id: 'line-158', speaker: '지수', text: '봐.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-159', speaker: '영우', text: '아니', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-160', speaker: '지수', text: '방금 인정했어.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-161', speaker: '영우', text: '아니아니아니', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-162', speaker: '지수', text: '잡았다.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-163', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 진짜 이게 왜 이렇게 돼', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-164', speaker: '지수', text: '영우야.', characterId: 'jisoo', expression: 'serious' },
  { id: 'line-165', speaker: '지수', text: '너 진짜 뭐 준비했지?', characterId: 'jisoo', expression: 'serious' },
  { id: 'line-166', speaker: '영우', text: '...', characterId: 'youngwoo', pauseBeforeMs: 400, expression: 'blank' },
  { id: 'line-167', speaker: '영우', text: '일단 밥 먹자', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-168', speaker: '지수', text: '미친.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-169', speaker: '', text: '둘 다 웃음을 터뜨린다.', characterId: null },
  { id: 'line-170', speaker: '영우', text: 'ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 진짜 배고프자나', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-171', speaker: '지수', text: '됐어요.\n일단 밥 먹어요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-172', speaker: '영우', text: '웅웅\n가자아', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-173', speaker: '지수', text: '근데 저 안 속았어요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-174', speaker: '영우', text: '뭘 안 속아', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-175', speaker: '지수', text: '몰라요.\n아직은.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-176', speaker: '지수', text: '근데 쌤 뭔가 있는 건 알아요.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-177', speaker: '영우', text: '와', characterId: 'youngwoo', expression: 'shocked' },
  { id: 'line-178', speaker: '영우', text: '진짜 무섭다 우리 지수', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-179', speaker: '지수', text: '그럼 잘해요.\n들키지 말고.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-180', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n알겠습니다', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-181', speaker: '', text: '지수의 첫날은,\n아직 평범한 여행에 가까웠다.', characterId: null }
];

/* OPERATION MK — WEEK 1 · SCENE 2-1 「진짜 같이 있네」
   Dialogue Set: dialogue-week1-scene002-1
   Scene: week1-scene-002-1 (Sydney Accommodation, 20:18)
   Ends on a MINIGAME START beat — nextSceneId hands off to the (not yet
   built) point-and-click phone-hunt scene, week1-scene-002-2. */
const week1Scene002_1Lines = [
  { id: 'line-001', speaker: '', text: '숙소.\n오후 8시 18분.', characterId: null },
  { id: 'line-002', speaker: '', text: '공항에서 나온 뒤,\n두 사람은 늦은 저녁을 간단히 먹고 숙소에 도착했다.', characterId: null },
  { id: 'line-003', speaker: '지수', text: '와.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-004', speaker: '지수', text: '잠깐만.\n여기 맞아요?', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-005', speaker: '영우', text: '웅웅.\n여기 맞아.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-006', speaker: '지수', text: '헐.\n아니 쌤, 생각보다 너무 좋은데요?', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-007', speaker: '영우', text: '그치그치 ㅎㅎㅎㅎㅎ\n사진보다 괜찮지 않아?', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-008', speaker: '지수', text: '아니 근데 잠깐.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-009', speaker: '영우', text: '웅?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-010', speaker: '지수', text: '쌤 이거 진짜 쌤이 잡은 거 맞아요?', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-011', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n왜 또 의심해 ㅎㅎㅎㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-012', speaker: '지수', text: '아니.\n너무 멀쩡해요.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-013', speaker: '영우', text: '숙소가 멀쩡하면 좋은 거 아니야?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-014', speaker: '지수', text: '그건 그렇긴 한데.\n쌤이 잡았잖아요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-015', speaker: '영우', text: '아놔 ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 지수야 내가 뭘 어떻게 살았길래', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-016', speaker: '지수', text: '그걸 제가 지금부터 설명해야 돼요?', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-017', speaker: '영우', text: '아니아니 됐어\n안 들을래 ㅎㅎㅎㅎㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-018', speaker: '', text: '영우가 카드키를 대고 문을 연다.', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-019', speaker: '지수', text: '헐.\n우와아아.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-020', speaker: '지수', text: '쌤 잠깐만.\n나 먼저 들어가도 돼요?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-021', speaker: '영우', text: '웅웅 들어가아 ㅎㅎㅎㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-022', speaker: '', text: '지수가 캐리어도 잊고 방 안으로 먼저 들어간다.', characterId: 'jisoo', expression: 'happy' },
  { id: 'line-023', speaker: '영우', text: '지수야 캐리어 ㅋㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-024', speaker: '지수', text: '아.\n쌤이 들고 있잖아요.', characterId: 'jisoo', expression: 'blank' },
  { id: 'line-025', speaker: '영우', text: '아 그러네\n왜 너무 자연스럽지', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-026', speaker: '지수', text: '적응 빠르죠?', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-027', speaker: '영우', text: '개빠르네 진짜 ㅎㅎㅎㅎㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-028', speaker: '지수', text: '오 이거 봐.\n창문도 크다.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-029', speaker: '영우', text: '웅웅.\n밤에 보면 더 이쁠 것 같더라구.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-030', speaker: '지수', text: '쌤 여기 와봐요.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-031', speaker: '', text: '영우가 창가 쪽으로 다가간다.', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-032', speaker: '지수', text: '아니 진짜 신기하다.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-033', speaker: '영우', text: '머가?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-034', speaker: '지수', text: '그냥.\n나 지금 시드니 숙소에 있고.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-035', speaker: '지수', text: '옆에 영우 있고.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-036', speaker: '지수', text: '내 캐리어는 영우가 들고 있고.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-037', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n마지막에 그게 왜 들어가', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-038', speaker: '지수', text: '중요하잖아.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-039', speaker: '영우', text: '아 그래그래\n아주 중요한 역사적 사건이지', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-040', speaker: '지수', text: '마자.\n기록해야 돼.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-041', speaker: '영우', text: '또 기록해? ㅋㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-042', speaker: '지수', text: '서영우 씨.\n호주 현지 적응 후 서비스 정신 향상.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-043', speaker: '영우', text: '미친 ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 그게 왜 현지 적응 결과야', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-044', speaker: '지수', text: '그럼 사랑의 힘?', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-045', speaker: '영우', text: '...', characterId: 'youngwoo', pauseBeforeMs: 400, expression: 'blank' },
  { id: 'line-046', speaker: '지수', text: '왜요.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-047', speaker: '영우', text: '그건 맞는 것 같아서', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-048', speaker: '지수', text: '...', characterId: 'jisoo', pauseBeforeMs: 300, expression: 'blank' },
  { id: 'line-049', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n왜애', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-050', speaker: '지수', text: '아니.\n그렇게 갑자기 진지하게 받으면 내가 뭐가 돼.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-051', speaker: '영우', text: '원래 좋았는데\n오늘은 지수가 진짜 앞에 있자나', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-052', speaker: '영우', text: '그래서 더 조아', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-053', speaker: '지수', text: '아 진짜.\n나도 너무 좋아.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-054', speaker: '', text: '잠깐 정적.', characterId: 'jisoo', pauseBeforeMs: 400, expression: 'soft' },
  { id: 'line-055', speaker: '영우', text: 'ㅎㅎㅎㅎㅎ\n이제 좀 실감 나?', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-056', speaker: '지수', text: '조금.\n근데 아직도 약간 꿈 같아.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-057', speaker: '영우', text: '나도.\n아까 공항에서도 계속 그 생각했어.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-058', speaker: '지수', text: '그래서 사람을 2분 동안 지켜봤다?', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-059', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 그걸 또 여기서 살리네', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-060', speaker: '지수', text: '안 죽었거든요.\n그 사건 아직 진행 중이에요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-061', speaker: '영우', text: '무슨 사건이야 ㅋㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-062', speaker: '지수', text: '시드니 공항 잠복 관찰 사건.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-063', speaker: '영우', text: '잠복 안 했다고 ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-064', speaker: '지수', text: '피의자는 그렇게 주장하고 있고요.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-065', speaker: '영우', text: '아 미치겠네 진짜', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-066', speaker: '지수', text: '현재 피의자는 웃음으로 진술을 회피 중.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-067', speaker: '영우', text: 'ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 지수야 그만해 배아파', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-068', speaker: '지수', text: '자백하세요.\n저 귀여워서 보고 있었다고.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-069', speaker: '영우', text: '그건 이미 했자나', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-070', speaker: '영우', text: '귀여웠어.\n개귀여웠어 진짜.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-071', speaker: '지수', text: '아.\n됐어.', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-072', speaker: '영우', text: '왜왜 ㅎㅎㅎㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-073', speaker: '지수', text: '자백 받아냈으니까.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-074', speaker: '', text: '영우가 캐리어를 침대 옆에 세운다.', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-075', speaker: '영우', text: '근데 지수 진짜 안 피곤해?', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-076', speaker: '지수', text: '피곤하긴 해.\n근데 신나서 잘 모르겠어.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-077', speaker: '영우', text: '아구.\n그래도 오늘 오래 탔자나.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-078', speaker: '지수', text: '쌤은요?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-079', speaker: '영우', text: '나는 괜찮지.', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-080', speaker: '지수', text: '거짓말.\n쌤도 피곤하잖아요.\n오늘 일도 했고.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-081', speaker: '영우', text: '아 그건...', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-082', speaker: '지수', text: '봐.\n말 끊겼어.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-083', speaker: '영우', text: '앜ㅎㅋㅎㅋㅎㅋㅎㅋㅎ\n아니 근데 지수가 왔는데 어떻게 자', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-084', speaker: '영우', text: '아까워.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-085', speaker: '지수', text: '영우야.\n나 안 가.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-086', speaker: '지수', text: '며칠 있잖아.\n오늘 다 안 놀아도 돼.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-087', speaker: '영우', text: '아.\n마자.\n그러네.', characterId: 'youngwoo', expression: 'blank' },
  { id: 'line-088', speaker: '지수', text: '왜 벌써 아쉬워해.', characterId: 'jisoo', expression: 'smirk' },
  { id: 'line-089', speaker: '영우', text: '몰라 ㅎㅎㅎㅎㅎ\n그냥 너무 기다렸나봐.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-090', speaker: '지수', text: '바부.', characterId: 'jisoo', expression: 'soft' },
  { id: 'line-091', speaker: '', text: '잠시 후.\n둘은 방 안에서 잠깐 쉬었다가 다시 나갈 준비를 시작했다.', characterId: null },
  { id: 'line-092', speaker: '지수', text: '쌤.\n우리 이제 나가요?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-093', speaker: '영우', text: '웅웅.\n지수 괜찮으면 근처만 좀 걷자.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-094', speaker: '지수', text: '좋아요.\n잠깐만.', characterId: 'jisoo', expression: 'neutral' },
  { id: 'line-095', speaker: '', text: '지수가 침대와 테이블 주변을 둘러본다.', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-096', speaker: '지수', text: '어?', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-097', speaker: '영우', text: '왜?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-098', speaker: '지수', text: '내 핸드폰 어디 갔지.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-099', speaker: '영우', text: '엉?', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-100', speaker: '지수', text: '잠깐.\n분명 아까 들고 있었는데.', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-101', speaker: '영우', text: '아 그래?\n어디다 뒀지', characterId: 'youngwoo', expression: 'curious' },
  { id: 'line-102', speaker: '지수', text: '쌤.', characterId: 'jisoo', expression: 'suspicious' },
  { id: 'line-103', speaker: '영우', text: '아니 왜 나 봐 ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-104', speaker: '지수', text: '아니 그냥.\n같이 찾아요.', characterId: 'jisoo', expression: 'neutral' },
  { id: 'line-105', speaker: '영우', text: '웅웅.\n찾아보자.', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-106', speaker: '', text: 'MINIGAME START', characterId: null },
];

/* OPERATION MK — WEEK 1 · SCENE 1-2 「지하철 역 찾기」
   Dialogue Set: dialogue-week1-scene001-2
   Scene: week1-scene-001-2 (Sydney Airport Station concourse, 09:45)
   Setup beat before the "find Eastwood station" route-map minigame —
   nextSceneId hands off to that minigame page directly (not another VN scene). */
const week1Scene001_2Lines = [
  { id: 'line-001', speaker: '영우', text: '자, 이제 숙소 가자.', characterId: 'youngwoo', expression: 'soft' },
  { id: 'line-002', speaker: '지수', text: '웅웅 ㅎㅎ\n우리 어디로 가야돼 여보?', characterId: 'jisoo', expression: 'happy' },
  { id: 'line-003', speaker: '영우', text: 'Eastwood역.', characterId: 'youngwoo', expression: 'neutral' },
  { id: 'line-004', speaker: '지수', text: '이스트우드으?', characterId: 'jisoo', expression: 'curious' },
  { id: 'line-005', speaker: '영우', text: '응. 노선도 보고 한번 찾아봐.', characterId: 'youngwoo', expression: 'smirk' },
  { id: 'line-006', speaker: '지수', text: '엥\n내가아아?????', characterId: 'jisoo', expression: 'shocked' },
  { id: 'line-007', speaker: '영우', text: '응 ㅋㅋㅋㅋ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-008', speaker: '지수', text: '아놔 여보 ㅋㅎㅋㅎㅋㅎㅋㅎ\n나 영어 못하는데에;;;;', characterId: 'jisoo', expression: 'annoyed' },
  { id: 'line-009', speaker: '영우', text: '역 이름만 찾으면 되잖아 ㅋㅋㅋㅋ', characterId: 'youngwoo', expression: 'happy' },
  { id: 'line-010', speaker: '지수', text: '아아 알게써 ㅠㅋㅋㅋㅋ\n어디보자아...\nEastwood...', characterId: 'jisoo', expression: 'blank', pauseBeforeMs: 200 },
];

// Registry of testable Week 1 scenes — /dev/week1 lists these, each linking
// to /dev/game/?scene=<id>. Add future scenes here as they're written.
const week1Scenes = [
  {
    id: 'week1-scene-001',
    order: 1,
    name: '진짜 왔네',
    location: 'Sydney Airport Arrival Area',
    introLabel: 'SYDNEY',
    time: '09:30',
    lines: week1Scene001Lines,
  },
  {
    id: 'week1-scene-001-2',
    order: 2,
    name: '지하철 역 찾기',
    location: 'Sydney Airport Station',
    introLabel: 'SYDNEY',
    time: '09:45',
    lines: week1Scene001_2Lines,
    // Hands off straight into the route-map minigame (not another VN scene) —
    // see MINIGAME_ROUTES in game/index.html. minigameId marks that this
    // scene has its own separate "미니게임" background slot in 배경 DB
    // (the route-map image), distinct from this scene's own VN background.
    nextSceneId: 'week1-scene-001-2-minigame',
    minigameId: 'week1-scene-001-2-minigame',
  },
  {
    id: 'week1-scene-002-1',
    order: 3,
    name: '진짜 같이 있네',
    location: 'Sydney Accommodation',
    introLabel: 'ACCOMMODATION',
    time: '20:18',
    lines: week1Scene002_1Lines,
    // Not a loop — this scene hands off to the point-and-click phone-hunt
    // minigame (week1-scene-002-2), which isn't built yet. See game/index.html.
    nextSceneId: 'week1-scene-002-2',
  },
];

// Groups scene registries by week — 배경 DB (/dev/upload) lists scenes under
// their week here instead of hardcoding a single week's worth of scenes.
const weeks = [
  { id: 'week1', label: '1주차', scenes: week1Scenes },
];
